version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: etsyviz
      POSTGRES_USER: etsyviz
      POSTGRES_PASSWORD: yTr97M8UTVBep0Q
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data in a named volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: Initialize DB
    networks:
      - app-network
    restart: always

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: etsyviz
      PGUSER: etsyviz
      PGPASSWORD: yTr97M8UTVBep0Q
    networks:
      - app-network
    restart: always

volumes:
  postgres-data:  # Named volume for persistent PostgreSQL data

networks:
  app-network: